#pragma once
#include<unordered_map>//std::unordered_map
#include<string>//std::string
std::unordered_map<std::string,std::string> const
language_of_extension={
    //A
    {".ada","Ada"},
    {".ADA","Ada"},
    {".adb","Ada"},
    {".ADB","Ada"},
    {".asm","Assembly"},
    {".ASM","Assembly"},
    {".masm","Assembly"},
    {".MASM","Assembly"},
    {".nasm","Assembly"},
    {".NASM","Assembly"},
    {".s","Assembly"},
    {".S","Assembly"},
    //B
    {".sh","Bourne Shell"},
    {".SH","Bourne Shell"},
    //C
    {".c","C"},
    {".C","C"},
    {".h","C/C++ Header"},
    {".H","C/C++ Header"},
    {".hh","C/C++ Header"},
    {".HH","C/C++ Header"},
    {".hpp","C/C++ Header"},
    {".HPP","C/C++ Header"},
    {".h++","C/C++ Header"},
    {".H++","C/C++ Header"},
    {".hxx","C/C++ Header"},
    {".HXX","C/C++ Header"},
    {".inl","C/C++ Header"},
    {".INL","C/C++ Header"},
    {".cc","C++"},
    {".CC","C++"},
    {".cpp","C++"},
    {".CPP","C++"},
    {".c++","C++"},
    {".C++","C++"},
    {".cxx","C++"},
    {".CXX","C++"},
    {".cs","C#"},
    {".CS","C#"},
    {".cob","COBOL"},
    {".COB","COBOL"},
    {".cbl","COBOL"},
    {".CBL","COBOL"},
    {".coffee","CoffeeScript"},
    {".COFFEE","CoffeeScript"},
    {".litcoffee","CoffeeScript"},
    {".LITCOFFEE","CoffeeScript"},
    {".lisp","Common Lisp"},
    {".LISP","Common Lisp"},
    {".cl","Common Lisp"},
    {".CL","Common Lisp"},
    {".clj","Clojure"},
    {".CLJ","Clojure"},
    {".cljc","Clojure"},
    {".CLJC","Clojure"},
    {".cljs","Clojure"},
    {".CLJS","Clojure"},
    //D
    {".d","D"},
    {".D","D"},
    {".dart","Dart"},
    {".DART","Dart"},
    //E
    {".erl","Erlang"},
    {".ERL","Erlang"},
    {".elisp","Emacs Lisp"},
    {".ELISP","Emacs Lisp"},
    //F
    {".fish","Fish Shell"},
    {".FISH","Fish Shell"},
    {".f","Fortran"},
    {".F","Fortran"},
    {".f90","Fortran"},
    {".F90","Fortran"},
    {".f03","Fortran"},
    {".F03","Fortran"},
    {".f08","Fortran"},
    {".F08","Fortran"},
    {".f2003","Fortran"},
    {".F2003","Fortran"},
    {".f2008","Fortran"},
    {".F2008","Fortran"},
    {".for","Fortran"},
    {".FOR","Fortran"},
    {".fpp","Fortran"},
    {".FPP","Fortran"},
    {".fs","F#"},
    {".FS","F#"},
    //G
    {".go","Go"},
    {".GO","Go"},
    {".gd","GDScript"},
    {".GD","GDScript"},
    {".groovy","Groovy"},
    {".GROOVY","Groovy"},
    //H
    {".hs","Haskell"},
    {".HS","Haskell"},
    //I
    //J
    {".java","Java"},
    {".JAVA","Java"},
    {".js","JavaScript"},
    {".JS","JavaScript"},
    {".jl","Julia"},
    {".JL","Julia"},
    //K
    {".kt","Kotlin"},
    {".KT","Kotlin"},
    //L
    {".lua","Lua"},
    {".LUA","Lua"},
    //M
    //N
    //O
    {".m","Objective-C"},
    {".M","Objective-C"},
    {".mm","Objective-C++"},
    {".MM","Objective-C++"},
    {".ml","OCaml"},
    {".ML","OCaml"},
    {".mli","OCaml"},
    {".MLI","OCaml"},
    //P
    {".pas","Pascal"},
    {".PAS","Pascal"},
    {".pl","Perl"},
    {".PL","Perl"},
    {".php","PHP"},
    {".PHP","PHP"},
    {".ps1","PowerShell"},
    {".PS1","PowerShell"},
    {".py","Python"},
    {".PY","Python"},
    //Q
    //R
    {".r","R"},
    {".R","R"},
    {".pl6","Raku"},
    {".PL6","Raku"},
    {".raku","Raku"},
    {".RAKU","Raku"},
    {".rb","Ruby"},
    {".RB","Ruby"},
    {".rs","Rust"},
    {".RS","Rust"},
    {".rkt","Racket"},
    {".RKT","Racket"},
    {".rktl","Racket"},
    {".RKTL","Racket"},
    {".rkts","Racket"},
    {".RKTS","Racket"},
    //S
    {".scala","Scala"},
    {".SCALA","Scala"},
    {".sql","SQL"},
    {".SQL","SQL"},
    {".swift","Swift"},
    {".SWIFT","Swift"},
    //T
    {".ts","TypeScript"},
    {".TS","TypeScript"},
    //U
    //V
    {".vala","Vala"},
    {".VALA","Vala"},
    {".vb","Visual Basic"},
    {".VB","Visual Basic"},
    {".vbs","VBScript"},
    {".VBS","VBScript"},
    {".vim","VimScript"},
    {".VIM","VimScript"},
    //W
    //X
    //Y
    //Z
    {".zig","Zig"},
    {".ZIG","Zig"},
    {".zsh","Z Shell"},
    {".ZSH","Z Shell"}
};
